import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient, type SupabaseClient } from "npm:@supabase/supabase-js@2.116.0";
const URL=Deno.env.get("SUPABASE_URL")??"", KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ORIGINS=new Set(["https://lucasrx08.github.io","https://dossard-pro.lucasrigaux8.chatgpt.site","http://localhost:3000","http://127.0.0.1:3000"]);
type J=Record<string,unknown>;
const txt=(v:unknown,n=160)=>String(v??"").trim().slice(0,n);
const arr=(v:unknown,n=200)=>Array.isArray(v)?[...new Set(v.map(x=>txt(x)).filter(Boolean))].slice(0,n):[];
const client=()=>createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
function cors(r:Request){const o=r.headers.get("origin")??"";return{"Access-Control-Allow-Origin":ORIGINS.has(o)?o:"https://lucasrx08.github.io","Access-Control-Allow-Headers":"apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"};}
function res(r:Request,p:unknown,s=200){return new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"no-store"}})}
function fail(m:string,s=400):never{throw Object.assign(new Error(m),{status:s})}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function joinCode(){const bytes=crypto.getRandomValues(new Uint32Array(1));return String(100000+(bytes[0]%900000))}
function validJoinCode(code:string){return /^\d{6}$/.test(code)||/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{8}$/.test(code)}
async function uniqueJoinCode(c:SupabaseClient){for(let attempt=0;attempt<12;attempt++){const code=joinCode(),hash=await sha(code);const q=await c.from("cross_heats").select("id").eq("station_code_hash",hash).limit(1).maybeSingle();if(q.error)throw q.error;if(!q.data)return code}fail("CODE_GENERATION_IMPOSSIBLE",503)}
const bib=(v:unknown)=>txt(v,40).normalize("NFKC").toUpperCase().replace(/[§_‐‑‒–—−﹘﹣－]/g,"-").replace(/\s+/g,"");
async function ownerHash(b:J){const k=txt(b.ownerKey,200);if(k.length<32)fail("CLE_ORGANISATEUR_INVALIDE",401);return sha(k)}
async function ownedEvent(c:SupabaseClient,id:string,h:string){const{data,error}=await c.from("cross_events").select("*").eq("id",id).eq("owner_key_hash",h).maybeSingle();if(error)throw error;if(!data)fail("EVENEMENT_INTROUVABLE",404);return data}
async function ownedHeat(c:SupabaseClient,id:string,h:string){const{data,error}=await c.from("cross_heats").select("*,event:cross_events!inner(id,name,owner_key_hash)").eq("id",id).eq("event.owner_key_hash",h).maybeSingle();if(error)throw error;if(!data)fail("COURSE_INTROUVABLE",404);return data}
async function heatByCode(c:SupabaseClient,code:string){code=code.toUpperCase();if(!validJoinCode(code))fail("CODE_INVALIDE",404);const{data,error}=await c.from("cross_heats").select("id,name,status,next_position,started_at,finished_at,event:cross_events(name)").eq("station_code_hash",await sha(code)).maybeSingle();if(error)throw error;if(!data)fail("CODE_INVALIDE",404);return data}
async function recompute(c:SupabaseClient,heatId:string){const{error}=await c.rpc("cross_recompute_segmented_positions",{p_heat_id:heatId});if(error)throw error}
async function syncEvent(b:J){const c=client(),h=await ownerHash(b),e=b.event as J;if(!e||typeof e!=="object")fail("EVENEMENT_REQUIS");const ps=Array.isArray(e.participants)?e.participants:[],local=txt(e.id,120),name=txt(e.name);if(!local||!name||!ps.length)fail("EVENEMENT_INCOMPLET");const rec={owner_id:null,owner_key_hash:h,local_event_id:local,name,year:Number(e.year)||new Date().getFullYear(),location:txt(e.location),event_date:txt(e.date,10)||null,scoring_mode:"rank",dnf_penalty_offset:10};const{data:ev,error}=await c.from("cross_events").upsert(rec,{onConflict:"owner_key_hash,local_event_id"}).select("*").single();if(error)throw error;const rows=ps.map(x=>{const p=x as J;return{event_id:ev.id,local_participant_id:txt(p.id,120),bib_code:bib(p.technicalId),bib_number:Number(p.bibNumber)||0,last_name:txt(p.lastName),first_name:txt(p.firstName),class_name:txt(p.className),sex:txt(p.sex,40)}});for(let i=0;i<rows.length;i+=350){const{error}=await c.from("cross_participants").upsert(rows.slice(i,i+350),{onConflict:"event_id,local_participant_id"});if(error)throw error}return{event:ev,participantCount:rows.length}}
async function ownerState(b:J){const c=client(),h=await ownerHash(b);const{data:event,error}=await c.from("cross_events").select("*").eq("owner_key_hash",h).eq("local_event_id",txt(b.localEventId,120)).maybeSingle();if(error)throw error;if(!event)return{event:null,heats:[]};const{data:heats,error:he}=await c.from("cross_heats").select("*").eq("event_id",event.id).order("created_at",{ascending:false});if(he)throw he;const ids=(heats??[]).map(x=>x.id);let es:any[]=[];if(ids.length){const q=await c.from("cross_entries").select("heat_id,status").in("heat_id",ids);if(q.error)throw q.error;es=q.data??[]}return{event,heats:(heats??[]).map(x=>{const z=es.filter(e=>e.heat_id===x.id);return{...x,counts:{total:z.length,registered:z.filter(e=>e.status==="registered").length,finished:z.filter(e=>e.status==="finished").length,dnf:z.filter(e=>e.status==="dnf").length,exempt:z.filter(e=>e.status==="exempt").length,absent:z.filter(e=>e.status==="absent").length}}})}}
async function saveHeatPlan(b:J){
  const c=client(),h=await ownerHash(b),eventId=txt(b.eventId,80),heatId=txt(b.heatId,80);
  await ownedEvent(c,eventId,h);
  const time=txt(b.scheduledTime,8);
  if(time&&!/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/.test(time))fail("HORAIRE_INVALIDE");
  const{data,error}=await c.rpc("cross_save_heat_plan_internal",{
    p_event_id:eventId,p_owner_key_hash:h,p_heat_id:heatId||null,p_name:txt(b.name),
    p_selected_classes:arr(b.selectedClasses),p_sex_filter:txt(b.sexFilter,10)||"all",
    p_challenge_enabled:Boolean(b.challengeEnabled),p_challenge_classes:arr(b.challengeClasses),
    p_participant_ids:arr(b.participantIds,5000),p_scheduled_time:time||null
  });
  if(error)throw error;
  return data;
}
async function startHeat(b:J){const c=client(),h=await ownerHash(b),id=txt(b.heatId,80),heat=await ownedHeat(c,id,h);if(heat.status!=="draft")fail("COURSE_DEJA_DEMARREE");const code=await uniqueJoinCode(c);const{data,error}=await c.from("cross_heats").update({status:"running",station_code_hash:await sha(code),started_at:new Date().toISOString(),finished_at:null,next_position:0}).eq("id",id).select("*").single();if(error)throw error;return{heat,stationCode:code}}
async function finishHeat(b:J){const c=client(),h=await ownerHash(b),id=txt(b.heatId,80);await ownedHeat(c,id,h);await c.from("cross_entries").update({status:"dnf"}).eq("heat_id",id).eq("status","registered");await c.from("cross_stations").update({status:"closed",updated_at:new Date().toISOString()}).eq("heat_id",id);const{error}=await c.from("cross_heats").update({status:"finished",finished_at:new Date().toISOString()}).eq("id",id);if(error)throw error;return{finished:true}}
async function heatEntries(b:J){const c=client(),h=await ownerHash(b),id=txt(b.heatId,80),heat=await ownedHeat(c,id,h);const q=await c.from("cross_entries").select("id,status,finish_position,station_order,station_position,elapsed_ms,scanned_at,station_id,participant:cross_participants(id,local_participant_id,bib_code,bib_number,last_name,first_name,class_name,sex)").eq("heat_id",id).order("finish_position",{ascending:true,nullsFirst:false});if(q.error)throw q.error;const s=await c.from("cross_stations").select("id,client_station_id,station_order,mode,status,created_at").eq("heat_id",id).order("station_order");if(s.error)throw s.error;return{heat,entries:q.data??[],stations:s.data??[]}}
async function setStatus(b:J){const c=client(),h=await ownerHash(b),id=txt(b.entryId,80),status=txt(b.status,20);if(!["registered","dnf","exempt","absent"].includes(status))fail("STATUT_INVALIDE");const q=await c.from("cross_entries").select("id,status,heat_id").eq("id",id).maybeSingle();if(q.error)throw q.error;if(!q.data)fail("PARTICIPANT_INTROUVABLE",404);await ownedHeat(c,q.data.heat_id,h);if(q.data.status==="finished")fail("SUPPRIMER_ARRIVEE_DABORD");const u=await c.from("cross_entries").update({status}).eq("id",id);if(u.error)throw u.error;return{ok:true}}
async function removeFinish(b:J){const c=client(),h=await ownerHash(b),id=txt(b.entryId,80);const q=await c.from("cross_entries").select("id,heat_id,status").eq("id",id).maybeSingle();if(q.error)throw q.error;if(!q.data)fail("ARRIVEE_INTROUVABLE",404);await ownedHeat(c,q.data.heat_id,h);await c.from("cross_scans").delete().eq("entry_id",id);await c.from("cross_entries").update({status:"registered",finish_position:null,station_order:null,station_position:null,elapsed_ms:null,scanned_at:null,station_id:null}).eq("id",id);await recompute(c,q.data.heat_id);return{removed:true}}
async function reorder(b:J){const c=client(),h=await ownerHash(b),id=txt(b.entryId,80),target=Number(b.position);if(!Number.isInteger(target)||target<1)fail("POSITION_INVALIDE");const q=await c.from("cross_entries").select("id,heat_id,finish_position").eq("id",id).maybeSingle();if(q.error)throw q.error;if(!q.data?.finish_position)fail("ARRIVEE_INTROUVABLE");const heat=await ownedHeat(c,q.data.heat_id,h);if(heat.status!=="finished")fail("TERMINER_LA_COURSE_DABORD");const all=await c.from("cross_entries").select("id,finish_position").eq("heat_id",q.data.heat_id).eq("status","finished").order("finish_position");if(all.error)throw all.error;const ids=(all.data??[]).map(x=>x.id).filter(x=>x!==id);ids.splice(Math.min(target-1,ids.length),0,id);for(let i=0;i<ids.length;i++)await c.from("cross_entries").update({finish_position:i+1}).eq("id",ids[i]);return{reordered:true}}
async function deleteHeat(b:J){const c=client(),h=await ownerHash(b),id=txt(b.heatId,80),heat=await ownedHeat(c,id,h);if(heat.status==="running")fail("TERMINER_LA_COURSE_DABORD");const q=await c.from("cross_heats").delete().eq("id",id);if(q.error)throw q.error;return{deleted:true}}
async function joinStation(b:J){const c=client(),code=txt(b.stationCode,40).toUpperCase(),sid=txt(b.stationId,80),mode=txt(b.mode,12);if(!sid||!["start","continue"].includes(mode))fail("POSTE_INVALIDE");const heat=await heatByCode(c,code);if(heat.status!=="running")fail("COURSE_NON_DEMARREE");const old=await c.from("cross_stations").select("*").eq("heat_id",heat.id).eq("client_station_id",sid).maybeSingle();if(old.error)throw old.error;if(old.data)return{station:old.data};const all=await c.from("cross_stations").select("station_order").eq("heat_id",heat.id).order("station_order");if(all.error)throw all.error;const used=(all.data??[]).map(x=>x.station_order);let order:number;if(mode==="start"){if(used.includes(1))fail("POSTE_DEBUT_DEJA_PRIS");order=1}else{if(!used.includes(1))fail("POSTE_DEBUT_REQUIS");order=Math.max(1,...used)+1;if(order>4)fail("MAX_POSTES_ATTEINT")}const ins=await c.from("cross_stations").insert({heat_id:heat.id,client_station_id:sid,station_order:order,mode}).select("*").single();if(ins.error)throw ins.error;return{station:ins.data}}
async function stationState(b:J){const c=client(),code=txt(b.stationCode,40).toUpperCase(),sid=txt(b.stationId,80),heat=await heatByCode(c,code);const st=await c.from("cross_stations").select("id,client_station_id,station_order,mode,status").eq("heat_id",heat.id).order("station_order");if(st.error)throw st.error;const statuses=await c.from("cross_entries").select("status").eq("heat_id",heat.id);if(statuses.error)throw statuses.error;const recent=await c.from("cross_entries").select("id,finish_position,station_order,station_position,elapsed_ms,scanned_at,station_id,participant:cross_participants(bib_code,first_name,last_name,class_name)").eq("heat_id",heat.id).eq("status","finished").order("scanned_at",{ascending:false}).limit(30);if(recent.error)throw recent.error;const z=statuses.data??[];return{heat,stations:st.data??[],myStation:(st.data??[]).find(x=>x.client_station_id===sid)??null,counts:{total:z.length,finished:z.filter(x=>x.status==="finished").length,dnf:z.filter(x=>x.status==="dnf").length,exempt:z.filter(x=>x.status==="exempt").length,absent:z.filter(x=>x.status==="absent").length},recent:recent.data??[]}}
async function scan(b:J){const c=client(),code=txt(b.stationCode,40).toUpperCase(),codeBib=bib(b.bibCode),sid=txt(b.stationId,80);if(!codeBib||!sid)fail("SCAN_INVALIDE");if(!validJoinCode(code))fail("CODE_INVALIDE",404);const{data,error}=await c.rpc("cross_register_segmented_scan_internal",{p_station_code_hash:await sha(code),p_bib_code:codeBib,p_station_id:sid});if(error)throw error;return{arrival:data?.[0]??null}}
async function undoLast(b:J){const c=client(),code=txt(b.stationCode,40).toUpperCase(),sid=txt(b.stationId,80),heat=await heatByCode(c,code);const s=await c.from("cross_stations").select("station_order").eq("heat_id",heat.id).eq("client_station_id",sid).maybeSingle();if(s.error)throw s.error;if(!s.data)fail("POSTE_NON_ENREGISTRE");const e=await c.from("cross_entries").select("id").eq("heat_id",heat.id).eq("status","finished").eq("station_order",s.data.station_order).order("station_position",{ascending:false}).limit(1).maybeSingle();if(e.error)throw e.error;if(!e.data)fail("AUCUNE_ARRIVEE_A_ANNULER");await c.from("cross_scans").delete().eq("entry_id",e.data.id);await c.from("cross_entries").update({status:"registered",finish_position:null,station_order:null,station_position:null,elapsed_ms:null,scanned_at:null,station_id:null}).eq("id",e.data.id);await recompute(c,heat.id);return{removed:true}}
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response(null,{status:204,headers:cors(r)});if(r.method!=="POST")return res(r,{error:"METHODE_INVALIDE"},405);const o=r.headers.get("origin");if(o&&!ORIGINS.has(o))return res(r,{error:"ORIGINE_INTERDITE"},403);try{const b=await r.json() as J,a=txt(b.action,60);const H:Record<string,()=>Promise<unknown>>={sync_event:()=>syncEvent(b),owner_state:()=>ownerState(b),create_heat:()=>saveHeatPlan(b),update_heat:()=>saveHeatPlan(b),start_heat:()=>startHeat(b),finish_heat:()=>finishHeat(b),heat_entries:()=>heatEntries(b),set_entry_status:()=>setStatus(b),remove_finish:()=>removeFinish(b),reorder_finish:()=>reorder(b),delete_heat:()=>deleteHeat(b),join_station:()=>joinStation(b),station_state:()=>stationState(b),scan:()=>scan(b),undo_last_scan:()=>undoLast(b)};if(!H[a])return res(r,{error:"ACTION_INCONNUE"},404);return res(r,{data:await H[a]()})}catch(e){const raw=e instanceof Error?e.message:typeof e==="object"&&e&&"message" in e?String(e.message):"ERREUR_SERVEUR",status=typeof e==="object"&&e&&"status" in e?Number((e as any).status):400;const known=raw.match(/(HORAIRE_INVALIDE|NOM_COURSE_REQUIS|FILTRE_INVALIDE|CODE_INVALIDE|CODE_GENERATION_IMPOSSIBLE|COURSE_NON_DEMARREE|DOSSARD_INCONNU|DOSSARD_DEJA_SCANNÉ|PARTICIPANT_DISPENSÉ|PARTICIPANT_ABSENT|CLE_ORGANISATEUR_INVALIDE|EVENEMENT_INTROUVABLE|COURSE_INTROUVABLE|AUCUN_PARTICIPANT|COURSE_DEJA_DEMARREE|SUPPRIMER_ARRIVEE_DABORD|TERMINER_LA_COURSE_DABORD|PARTICIPANT_INTROUVABLE|ARRIVEE_INTROUVABLE|POSTE_NON_ENREGISTRE|POSTE_INVALIDE|POSTE_DEBUT_DEJA_PRIS|POSTE_DEBUT_REQUIS|MAX_POSTES_ATTEINT|AUCUNE_ARRIVEE_A_ANNULER)/)?.[1];console.error(raw);return res(r,{error:known??"ERREUR_SERVEUR"},Number.isFinite(status)?status:400)}});
