import * as XLSX from "xlsx";
import { createLocalId, technicalId } from "./identifiers";
import type { ColumnMapping, ImportDraft, NumberingConfig, Participant, ParticipantField } from "./types";
import { validateParticipants } from "./validation";
export const participantFields: Array<{ key: ParticipantField; label: string; required: boolean }> = [{ key: "lastName", label: "Nom", required: true }, { key: "firstName", label: "Prénom", required: true }, { key: "className", label: "Classe", required: true }, { key: "sex", label: "Sexe", required: false }];
const normalized = (value: unknown) => String(value ?? "").trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]/g, "");
const aliases: Record<ParticipantField, string[]> = { lastName: ["nom", "nomdeleleve", "nomeleve", "nomfamille", "lastname", "surname", "eleve"], firstName: ["prenom", "prenomdeleleve", "prenomeleve", "firstname", "givenname"], className: ["classe", "groupe", "class", "niveau", "division"], sex: ["sexe", "genre", "sex", "gender"] };
function suggestMapping(headers: string[]): ColumnMapping { const mapping: ColumnMapping = {}, used = new Set<number>(); for (const field of participantFields) { let index = headers.findIndex((header, i) => !used.has(i) && aliases[field.key].includes(normalized(header))); if (index < 0) { const safeAliases = aliases[field.key].filter((alias) => alias.length >= 5 && !["eleve","prenom"].includes(alias)); index = headers.findIndex((header, i) => !used.has(i) && safeAliases.some((alias) => normalized(header).includes(alias))); } if (index >= 0) { mapping[field.key] = index; used.add(index); } } return mapping; }
export async function readParticipantFile(file: File): Promise<ImportDraft> { const isCsv = file.name.toLowerCase().endsWith(".csv") || file.type.includes("csv"); const workbook = isCsv ? XLSX.read(await file.text(), { type: "string", cellDates: true }) : XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }); const name = workbook.SheetNames[0]; if (!name) throw new Error("Le fichier ne contient aucune feuille."); const raw = XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[name], { header: 1, raw: false, defval: "", blankrows: false }); const rows = raw.filter((row) => row.some((cell) => String(cell ?? "").trim())); if (rows.length < 2) throw new Error("Ajoutez une ligne d’en-têtes et au moins un participant."); const headers = rows[0].map((cell, index) => String(cell || `Colonne ${index + 1}`).trim()); return { fileName: file.name, headers, rows: rows.slice(1), mapping: suggestMapping(headers) }; }
const valueAt = (row: unknown[], index?: number) => typeof index === "number" && index >= 0 ? String(row[index] ?? "").trim() : "";
export const mappingIsValid = (mapping: ColumnMapping) => [mapping.lastName, mapping.firstName, mapping.className].every((index) => typeof index === "number" && index >= 0);
export function importParticipants(draft: ImportDraft, mapping: ColumnMapping, numbering: NumberingConfig): Participant[] { return validateParticipants(draft.rows.map((row, index) => { const bibNumber = numbering.start + index; return { id: createLocalId(), sourceRow: index + 2, bibNumber, technicalId: technicalId(numbering, bibNumber), lastName: valueAt(row, mapping.lastName), firstName: valueAt(row, mapping.firstName), className: valueAt(row, mapping.className), sex: valueAt(row, mapping.sex) || undefined, issues: [] }; })); }
