import fontkit from "@pdf-lib/fontkit";
import { degrees, PDFDocument, type PDFFont, type PDFImage, type PDFPage, rgb } from "pdf-lib";
import { barcodeGeometry } from "./barcode";
import { shortNumber } from "./identifiers";
import { createQrMatrix, qrRuns } from "./qr";
import type { LayoutElement, Participant, PdfProgress, RaceEvent } from "./types";
import { publicAsset } from "./assets";

const PT = 72 / 25.4;
const mm = (value: number) => value * PT;
function color(hex: string) { const raw = hex.replace("#", ""); const full = raw.length === 3 ? raw.split("").map((c) => c + c).join("") : raw.padEnd(6, "0").slice(0, 6); return rgb(parseInt(full.slice(0, 2), 16) / 255, parseInt(full.slice(2, 4), 16) / 255, parseInt(full.slice(4, 6), 16) / 255); }
function textValue(element: LayoutElement, p: Participant, event: RaceEvent) { switch (element.type) { case "number": return shortNumber(p.bibNumber, event.numbering.digits); case "lastName": return p.lastName; case "firstName": return p.firstName; case "fullName": return `${p.lastName.toLocaleUpperCase("fr")} ${p.firstName}`.trim(); case "className": return p.className; case "sex": return p.sex ?? ""; case "freeText": return (element.content ?? "").replaceAll("{{event}}", event.name).replaceAll("{{year}}", String(event.year)).replaceAll("{{lieu}}", event.location); default: return ""; } }
function fit(font: PDFFont, text: string, preferred: number, minimum: number, width: number) { let size = Math.max(4, preferred); const floor = Math.max(4, Math.min(minimum, preferred)); while (size > floor && font.widthOfTextAtSize(text, size) > width) size -= .5; while (size > 4 && font.widthOfTextAtSize(text, size) > width) size -= .5; return size; }
async function font(path: string) { const response = await fetch(path); if (!response.ok) throw new Error("Police d’impression indisponible."); return response.arrayBuffer(); }
function defaultBackground(page: PDFPage, width: number, height: number, originY: number) { page.drawRectangle({ x: 0, y: originY, width, height, color: rgb(1,1,1) }); page.drawRectangle({ x: 0, y: originY + height - mm(4), width, height: mm(4), color: rgb(1,.82,0) }); page.drawRectangle({ x: mm(3), y: originY + mm(3), width: width - mm(6), height: height - mm(6), borderColor: rgb(0,.29,.7), borderWidth: mm(.7) }); }
function imageContained(page: PDFPage, image: PDFImage, width: number, height: number, originY: number) { const scale = Math.min(width / image.width, height / image.height), w = image.width * scale, h = image.height * scale; page.drawImage(image, { x: (width - w) / 2, y: originY + (height - h) / 2, width: w, height: h }); }
function drawText(page: PDFPage, pageHeight: number, originY: number, element: LayoutElement, text: string, regular: PDFFont, bold: PDFFont) { if (!text) return false; const selected = element.bold ? bold : regular, x = mm(element.xMm), width = mm(element.widthMm), height = mm(element.heightMm), bottom = originY + pageHeight - mm(element.yMm) - height, size = fit(selected, text, element.fontSizePt, element.minFontSizePt, Math.max(1, width - mm(1.6))), textWidth = selected.widthOfTextAtSize(text, size), textX = element.align === "center" ? x + (width - textWidth) / 2 : element.align === "right" ? x + width - textWidth - mm(.8) : x + mm(.8); page.drawText(text, { x: textX, y: bottom + Math.max(0, (height - size) / 2) + size * .12, size, font: selected, color: color(element.color), xSkew: element.italic ? degrees(12) : undefined }); return size < element.fontSizePt; }
function drawBarcode(page: PDFPage, pageHeight: number, originY: number, element: LayoutElement, value: string, regular: PDFFont) { const geometry = barcodeGeometry(value), x = mm(element.xMm), width = mm(element.widthMm), height = mm(element.heightMm), bottom = originY + pageHeight - mm(element.yMm) - height, label = element.showHumanReadable ? mm(4.2) : 0, moduleWidth = width / geometry.totalModules; page.drawRectangle({ x, y: bottom, width, height, color: rgb(1,1,1) }); for (const bar of geometry.bars) page.drawRectangle({ x: x + bar.x * moduleWidth, y: bottom + label, width: bar.width * moduleWidth, height: Math.max(mm(5), height - label), color: rgb(0,0,0) }); if (element.showHumanReadable) { const size = Math.min(7, Math.max(4.5, element.fontSizePt)), w = regular.widthOfTextAtSize(value, size); page.drawText(value, { x: x + Math.max(mm(1), (width - w) / 2), y: bottom + mm(.7), size, font: regular }); } }
function drawQr(page: PDFPage, pageHeight: number, originY: number, element: LayoutElement, value: string) { const matrix = createQrMatrix(value), requestedW = mm(element.widthMm), requestedH = mm(element.heightMm), size = Math.min(requestedW, requestedH), total = matrix.size + 8, moduleSize = size / total, x = mm(element.xMm) + (requestedW - size) / 2, bottom = originY + pageHeight - mm(element.yMm) - requestedH + (requestedH - size) / 2; page.drawRectangle({ x, y: bottom, width: size, height: size, color: rgb(1,1,1) }); for (const run of qrRuns(matrix)) page.drawRectangle({ x: x + (4 + run.start) * moduleSize, y: bottom + (4 + matrix.size - run.row - 1) * moduleSize, width: run.length * moduleSize, height: moduleSize, color: rgb(0,0,0) }); }
export async function generateBibPdf(event: RaceEvent, participants: Array<Participant | null>, onProgress?: (progress: PdfProgress) => void) { if (!participants.some(Boolean)) throw new Error("Aucun participant dans cette sélection."); onProgress?.({ completed: 0, total: participants.length, phase: "preparing" }); const document = await PDFDocument.create(); document.registerFontkit(fontkit); document.setTitle(`${event.name} — Dossards A4`); document.setCreator("Bon Sauveur Cross"); const [regularBytes, boldBytes] = await Promise.all([font(publicAsset("/fonts/DejaVuSans.ttf")), font(publicAsset("/fonts/DejaVuSans-Bold.ttf"))]); const [regular, bold] = await Promise.all([document.embedFont(regularBytes, { subset: true }), document.embedFont(boldBytes, { subset: true })]); let background: PDFImage | undefined; if (event.template.background) { const bytes = await fetch(event.template.background.dataUrl).then((r) => r.arrayBuffer()); background = event.template.background.mimeType === "image/png" ? await document.embedPng(bytes) : await document.embedJpg(bytes); } const bibWidth = mm(event.template.widthMm), bibHeight = mm(event.template.heightMm), a4Width = mm(210), a4Height = mm(297); let reducedTextParticipants = 0; for (let sheetIndex = 0; sheetIndex < participants.length; sheetIndex += 2) { const page = document.addPage([a4Width, a4Height]); page.drawLine({ start:{x:0,y:mm(148.5)}, end:{x:a4Width,y:mm(148.5)}, thickness:mm(.18), color:rgb(.72,.72,.72), dashArray:[mm(2),mm(2)] }); for (let slot = 0; slot < 2; slot += 1) { const index = sheetIndex + slot; if (index >= participants.length) break; const p = participants[index], originY = slot === 0 ? mm(149) : 0; if (!p) continue; if (background) imageContained(page, background, bibWidth, bibHeight, originY); else defaultBackground(page, bibWidth, bibHeight, originY); let reduced = false; for (const element of event.template.elements) { if (element.type === "barcode") drawBarcode(page, bibHeight, originY, element, p.technicalId, regular); else if (element.type === "qrcode") drawQr(page, bibHeight, originY, element, p.technicalId); else reduced = drawText(page, bibHeight, originY, element, textValue(element, p, event), regular, bold) || reduced; } if (reduced) reducedTextParticipants += 1; if (index % 10 === 0 || index === participants.length - 1) { onProgress?.({ completed: index + 1, total: participants.length, phase: "generating" }); await new Promise<void>((resolve) => setTimeout(resolve, 0)); } } } onProgress?.({ completed: participants.length, total: participants.length, phase: "saving" }); const bytes = await document.save({ useObjectStreams: true, objectsPerTick: 50 }); onProgress?.({ completed: participants.length, total: participants.length, phase: "done" }); return { bytes, reducedTextParticipants, a4PageCount: Math.ceil(participants.length / 2) }; }
