import type { BibTemplate, LayoutElement, Participant, RaceEvent } from "./types";
const DB_NAME = "dossard-pro-v1", DB_VERSION = 1, EVENTS_STORE = "events", TEMPLATES_STORE = "templates";
let databasePromise: Promise<IDBDatabase> | undefined;
function openDatabase(): Promise<IDBDatabase> { if (databasePromise) return databasePromise; databasePromise = new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(EVENTS_STORE)) db.createObjectStore(EVENTS_STORE, { keyPath: "id" }); if (!db.objectStoreNames.contains(TEMPLATES_STORE)) db.createObjectStore(TEMPLATES_STORE, { keyPath: "id" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("Stockage local indisponible.")); }); return databasePromise; }
function result<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("Opération locale impossible.")); }); }
async function getStore(mode: IDBTransactionMode, name: string) { const db = await openDatabase(); return db.transaction(name, mode).objectStore(name); }
const allowedElements = new Set(["number","lastName","firstName","fullName","className","sex","barcode","qrcode","freeText"]);
function cleanParticipant(p: Participant): Participant { return { id:p.id, sourceRow:p.sourceRow, bibNumber:p.bibNumber, technicalId:p.technicalId, lastName:p.lastName, firstName:p.firstName, className:p.className, sex:p.sex || undefined, issues:p.issues ?? [] }; }
function cleanTemplate(template: BibTemplate): BibTemplate { return { ...template, elements: template.elements.filter((element) => allowedElements.has(element.type)).map((element) => ({ ...element } as LayoutElement)) }; }
function cleanEvent(event: RaceEvent): RaceEvent { return { ...event, participants:event.participants.map(cleanParticipant), template:cleanTemplate(event.template) }; }
export async function listEvents(): Promise<RaceEvent[]> { const items = await result((await getStore("readonly", EVENTS_STORE)).getAll() as IDBRequest<RaceEvent[]>); return items.map(cleanEvent).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
export async function saveEvent(event: RaceEvent): Promise<RaceEvent> { const saved = { ...cleanEvent(event), updatedAt: new Date().toISOString() }; await result((await getStore("readwrite", EVENTS_STORE)).put(saved)); return saved; }
export async function deleteEvent(id: string) { await result((await getStore("readwrite", EVENTS_STORE)).delete(id)); }
export async function listTemplates(): Promise<BibTemplate[]> { const items = await result((await getStore("readonly", TEMPLATES_STORE)).getAll() as IDBRequest<BibTemplate[]>); return items.map(cleanTemplate).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
export async function saveTemplate(template: BibTemplate): Promise<BibTemplate> { const saved = { ...cleanTemplate(template), updatedAt: new Date().toISOString() }; await result((await getStore("readwrite", TEMPLATES_STORE)).put(saved)); return saved; }
