"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { BarcodePreview, QrPreview } from "./code-preview";
import { previewElementValue, previewParticipant } from "@/lib/dossard/preview";
import type { LayoutElement, Participant, RaceEvent } from "@/lib/dossard/types";
interface Props { event: RaceEvent; participant?: Participant; selectedId?: string; onSelect?: (id: string) => void; onChange?: (element: LayoutElement) => void; grid?: boolean; snap?: boolean; interactive?: boolean; }
interface Drag { mode: "move" | "resize"; element: LayoutElement; x: number; y: number; rect: DOMRect; }
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
const snapped = (value: number, enabled: boolean) => enabled ? Math.round(value) : Math.round(value * 10) / 10;
function fitSize(element: LayoutElement, text: string, pxPerMm: number) { if (typeof document === "undefined") return element.fontSizePt; const context = document.createElement("canvas").getContext("2d"); if (!context) return element.fontSizePt; let size = element.fontSizePt; while (size > 4) { const px = size * (25.4 / 72) * pxPerMm; context.font = `${element.italic ? "italic " : ""}${element.bold ? 700 : 400} ${px}px DejaVu Sans,Arial`; if (context.measureText(text).width <= Math.max(2, element.widthMm * pxPerMm - 8)) break; size -= .5; } return size; }
export function BibCanvas({ event, participant = previewParticipant, selectedId, onSelect, onChange, grid = true, snap = true, interactive = true }: Props) { const frameRef = useRef<HTMLDivElement>(null); const [drag, setDrag] = useState<Drag | null>(null); const [frameWidth, setFrameWidth] = useState(840); const template = event.template; useEffect(() => { const frame = frameRef.current; if (!frame) return; const observer = new ResizeObserver(([entry]) => setFrameWidth(entry.contentRect.width)); observer.observe(frame); return () => observer.disconnect(); }, []); useEffect(() => { if (!drag || !onChange) return; const move = (e: PointerEvent) => { const dx = (e.clientX - drag.x) * template.widthMm / drag.rect.width, dy = (e.clientY - drag.y) * template.heightMm / drag.rect.height; if (drag.mode === "move") { let x = snapped(drag.element.xMm + dx, snap), y = snapped(drag.element.yMm + dy, snap); if (snap && Math.abs(x + drag.element.widthMm / 2 - template.widthMm / 2) < 1.2) x = template.widthMm / 2 - drag.element.widthMm / 2; if (snap && Math.abs(y + drag.element.heightMm / 2 - template.heightMm / 2) < 1.2) y = template.heightMm / 2 - drag.element.heightMm / 2; onChange({ ...drag.element, xMm: clamp(x, 0, template.widthMm - drag.element.widthMm), yMm: clamp(y, 0, template.heightMm - drag.element.heightMm) }); } else onChange({ ...drag.element, widthMm: clamp(snapped(drag.element.widthMm + dx, snap), 6, template.widthMm - drag.element.xMm), heightMm: clamp(snapped(drag.element.heightMm + dy, snap), 6, template.heightMm - drag.element.yMm) }); }; const up = () => setDrag(null); window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, [drag, onChange, snap, template.heightMm, template.widthMm]); const pxPerMm = frameWidth / template.widthMm; const background = useMemo(() => template.background ? { backgroundImage: `url(${template.background.dataUrl})`, backgroundSize: "contain", backgroundPosition: "center", backgroundRepeat: "no-repeat", backgroundColor: "white" } : undefined, [template.background]); return <div ref={frameRef} onClick={() => interactive && onSelect?.("")} className="bib-canvas relative w-full overflow-hidden bg-white shadow-[0_24px_70px_rgba(10,22,43,.18)]" style={{ aspectRatio: `${template.widthMm}/${template.heightMm}`, ...background }}>
    {!template.background && <div aria-hidden className="pointer-events-none absolute inset-0 border-[clamp(2px,.35vw,6px)] border-[#1154b3]"><div className="absolute inset-x-0 top-0 h-[2.8%] bg-[#fed60b]" /></div>}
    {grid && interactive && <div aria-hidden className="pointer-events-none absolute inset-0 opacity-[.16]" style={{ backgroundImage: "linear-gradient(to right,#1154b3 1px,transparent 1px),linear-gradient(to bottom,#1154b3 1px,transparent 1px)", backgroundSize: `${pxPerMm * 5}px ${pxPerMm * 5}px` }} />}
    {template.elements.map((element) => { const text = previewElementValue(element, participant, event), selected = element.id === selectedId, fitted = fitSize(element, text, pxPerMm); return <div key={element.id} role={interactive ? "button" : undefined} tabIndex={interactive ? 0 : undefined} aria-label={interactive ? element.name : undefined} className={`absolute flex select-none items-center ${interactive ? "cursor-move touch-none" : ""} ${selected ? "z-20 outline-2 outline-offset-2 outline-[#fed60b]" : "z-10"}`} style={{ left: `${element.xMm / template.widthMm * 100}%`, top: `${element.yMm / template.heightMm * 100}%`, width: `${element.widthMm / template.widthMm * 100}%`, height: `${element.heightMm / template.heightMm * 100}%` }} onClick={(e) => { e.stopPropagation(); onSelect?.(element.id); }} onPointerDown={(e) => { if (!interactive || !onChange || !frameRef.current) return; e.preventDefault(); e.stopPropagation(); onSelect?.(element.id); setDrag({ mode: "move", element, x: e.clientX, y: e.clientY, rect: frameRef.current.getBoundingClientRect() }); }} onKeyDown={(e) => { if (!interactive || !onChange || !["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)) return; e.preventDefault(); const a = e.shiftKey ? .2 : 1; onChange({ ...element, xMm: clamp(element.xMm + (e.key === "ArrowLeft" ? -a : e.key === "ArrowRight" ? a : 0), 0, template.widthMm - element.widthMm), yMm: clamp(element.yMm + (e.key === "ArrowUp" ? -a : e.key === "ArrowDown" ? a : 0), 0, template.heightMm - element.heightMm) }); }}>
      {element.type === "barcode" ? <BarcodePreview value={participant.technicalId} showText={element.showHumanReadable} /> : element.type === "qrcode" ? <QrPreview value={participant.technicalId} /> : <span className="w-full whitespace-nowrap" style={{ color: element.color, fontSize: `${fitted * (25.4 / 72) * pxPerMm}px`, fontWeight: element.bold ? 700 : 400, fontStyle: element.italic ? "italic" : "normal", textAlign: element.align, lineHeight: 1 }}>{text}</span>}
      {selected && interactive && onChange && <button type="button" aria-label={`Redimensionner ${element.name}`} className="absolute -bottom-2 -right-2 size-7 cursor-nwse-resize rounded-full border-2 border-white bg-[#1154b3] shadow touch-none" onPointerDown={(e) => { if (!frameRef.current) return; e.preventDefault(); e.stopPropagation(); setDrag({ mode: "resize", element, x: e.clientX, y: e.clientY, rect: frameRef.current.getBoundingClientRect() }); }} />}
    </div>; })}
  </div>; }
