"use client";
import { useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, FileSpreadsheet, Pencil, Plus, Printer, Search, Trash2, UploadCloud, Users } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StepHeading } from "./step-heading";
import { MappingDialog } from "./mapping-dialog";
import { ParticipantDialog } from "./participant-dialog";
import { importParticipants, readParticipantFile } from "@/lib/dossard/import";
import { createLocalId, nextAvailableNumber, renumberParticipants, sanitizePrefix, technicalId } from "@/lib/dossard/identifiers";
import type { ColumnMapping, ImportDraft, Participant, RaceEvent } from "@/lib/dossard/types";
import { validateParticipants } from "@/lib/dossard/validation";
const PAGE_SIZE = 30;
type IssueFilter = "all" | "errors" | "warnings";
interface Props { event: RaceEvent; onChange: (event: RaceEvent) => void; selectedIds: Set<string>; onSelectedIdsChange: (ids: Set<string>) => void; onReprint: (id: string) => void; issueFilter: IssueFilter; onIssueFilterChange: (filter: IssueFilter) => void; }
export function ParticipantsStep({ event, onChange, selectedIds, onSelectedIdsChange, onReprint, issueFilter, onIssueFilterChange }: Props) {
 const fileRef = useRef<HTMLInputElement>(null); const [draft,setDraft] = useState<ImportDraft>(); const [mappingOpen,setMappingOpen] = useState(false); const [replacement,setReplacement] = useState<Participant[]>(); const [search,setSearch] = useState(""); const [classFilter,setClassFilter] = useState("all"); const [page,setPage] = useState(1); const [editorOpen,setEditorOpen] = useState(false); const [edited,setEdited] = useState<Participant|null>(null); const [deleteCandidate,setDeleteCandidate] = useState<Participant>(); const participants = event.participants;
 const classes = useMemo(() => [...new Set(participants.map((p) => p.className).filter(Boolean))].sort((a,b) => a.localeCompare(b,"fr")), [participants]);
 const errors = participants.reduce((sum,p) => sum + p.issues.filter((i) => i.severity === "error").length, 0), duplicates = participants.filter((p) => p.issues.some((i) => i.code === "possible-duplicate")).length;
 const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase("fr"); return participants.filter((p) => (!q || [p.lastName,p.firstName,p.className,p.technicalId].some((v) => v.toLocaleLowerCase("fr").includes(q))) && (classFilter === "all" || p.className === classFilter) && (issueFilter === "all" || (issueFilter === "errors" ? p.issues.some((i) => i.severity === "error") : p.issues.some((i) => i.severity === "warning")))); }, [participants,search,classFilter,issueFilter]); const pages = Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)), currentPage = Math.min(page,pages), visible = filtered.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
 const update = (next: Participant[]) => onChange({ ...event, participants: validateParticipants(next) });
 const processFile = async (file?: File) => { if (!file) return; try { const next = await readParticipantFile(file); setDraft(next); setMappingOpen(true); } catch (error) { toast.error(error instanceof Error ? error.message : "Import impossible."); } };
 const confirmMapping = (mapping: ColumnMapping) => { if (!draft) return; const imported = importParticipants(draft,mapping,event.numbering); setMappingOpen(false); if (participants.length) setReplacement(imported); else { onChange({ ...event, participants: imported, sourceFileName: draft.fileName }); toast.success(`${imported.length} participants importés.`); } };
 const number = (patch: Partial<RaceEvent["numbering"]>) => { const numbering = { ...event.numbering, ...patch }; numbering.prefix = sanitizePrefix(numbering.prefix); numbering.start = Math.max(0,Number.isFinite(numbering.start) ? numbering.start : 1); numbering.digits = Math.max(1,Math.min(8,Number.isFinite(numbering.digits) ? numbering.digits : 4)); onChange({ ...event, numbering, participants: validateParticipants(renumberParticipants(participants,numbering)) }); };
 const toggleVisible = (checked: boolean) => { const next = new Set(selectedIds); visible.forEach((p) => checked ? next.add(p.id) : next.delete(p.id)); onSelectedIdsChange(next); };
 return <div className="space-y-6">
  <StepHeading icon={Users} title="Participants" description="Importez votre liste, vérifiez les élèves et attribuez les numéros de dossard." />
  <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
   <div role="button" tabIndex={0} aria-label="Importer une liste de participants" className="group flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-[#f0f5ff] px-6 py-8 text-center outline-none transition-colors hover:border-primary focus-visible:ring-4 focus-visible:ring-primary/20" onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();fileRef.current?.click();}}} onClick={() => fileRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); void processFile(e.dataTransfer.files[0]); }}>
    <span className="cross-icon mb-4 size-14 bg-white shadow-sm"><UploadCloud className="size-6" /></span><h3 className="text-xl font-bold">{participants.length ? "Importer un nouveau fichier" : "Ajouter votre liste d’élèves"}</h3><p className="mt-2 text-sm text-muted-foreground">Nom, prénom, classe et sexe · Excel ou CSV</p><span className="mt-5 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-white">Choisir un fichier</span><p className="mt-3 text-xs text-muted-foreground">Vous pouvez aussi glisser votre fichier ici.</p><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={(e) => { void processFile(e.target.files?.[0]); e.target.value = ""; }} />
   </div>
   <aside className="cross-panel p-5"><div className="mb-5 flex items-center gap-3"><span className="cross-icon bg-[#fff5bc]"><FileSpreadsheet className="size-5" /></span><h3 className="font-bold">Numérotation des dossards</h3></div><div className="grid grid-cols-2 gap-4"><div className="col-span-2"><Label htmlFor="bib-prefix">Préfixe (facultatif)</Label><Input id="bib-prefix" value={event.numbering.prefix} maxLength={16} placeholder="Ex. CROSS, ou laisser vide" onChange={(e) => number({prefix:e.target.value})}/><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Laissez vide pour utiliser uniquement des chiffres.</p></div><div><Label htmlFor="bib-start">Premier numéro</Label><Input id="bib-start" type="number" value={event.numbering.start} onChange={(e) => number({start:Number(e.target.value)})}/></div><div><Label htmlFor="bib-digits">Chiffres</Label><Input id="bib-digits" type="number" min={1} max={8} value={event.numbering.digits} onChange={(e) => number({digits:Number(e.target.value)})}/></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#fff8d5] px-4 py-3"><span className="text-xs font-semibold text-[#756523]">Exemple de code</span><span className="font-mono text-xl font-bold text-[#173970]">{technicalId(event.numbering,event.numbering.start)}</span></div></aside>
  </section>
  <section aria-label="Bilan de la liste" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:"Participants",value:participants.length,icon:Users,tone:"blue"},{label:"Classes",value:classes.length,icon:CheckCircle2,tone:"blue"},{label:"Erreurs",value:errors,icon:AlertCircle,tone:errors?"red":"green"},{label:"Doublons potentiels",value:duplicates,icon:AlertCircle,tone:duplicates?"amber":"green"}].map((stat) => <div key={stat.label} className="cross-panel p-4"><div className="flex items-start justify-between gap-3"><span className="text-sm leading-5 text-muted-foreground">{stat.label}</span><stat.icon className={`mt-0.5 size-4 shrink-0 ${stat.tone === "red" ? "text-red-500" : stat.tone === "amber" ? "text-amber-500" : stat.tone === "green" ? "text-emerald-500" : "text-primary"}`}/></div><p className="mt-3 text-2xl font-bold tabular-nums">{stat.value}</p></div>)}</section>
  <section className="cross-panel overflow-hidden">
   <div className="grid gap-3 border-b p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_200px_200px_auto]"><div className="relative self-start sm:col-span-2 xl:col-span-1"><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input aria-label="Rechercher un participant" value={search} onChange={(e) => {setSearch(e.target.value);setPage(1);}} placeholder="Nom, classe ou numéro…" className="pl-10"/></div><Select value={classFilter} onValueChange={(v) => {setClassFilter(v);setPage(1);}}><SelectTrigger aria-label="Filtrer par classe"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les classes</SelectItem>{classes.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={issueFilter} onValueChange={(v) => {onIssueFilterChange(v as IssueFilter);setPage(1);}}><SelectTrigger aria-label="Filtrer les contrôles"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les lignes</SelectItem><SelectItem value="errors">Avec erreurs</SelectItem><SelectItem value="warnings">Avec alertes</SelectItem></SelectContent></Select><Button variant="outline" className="sm:col-span-2 xl:col-span-1" onClick={() => {setEdited(null);setEditorOpen(true);}}><Plus/>Ajouter un élève</Button></div>
   {!participants.length ? <div className="grid min-h-48 place-items-center p-8 text-center"><div><Users className="mx-auto mb-3 size-8 text-slate-300"/><p className="font-semibold">Votre liste est prête à être importée</p><p className="mt-1 text-sm text-muted-foreground">Vous pouvez aussi ajouter les élèves un par un.</p></div></div> : <>
    <div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-2"><label className="flex min-h-11 cursor-pointer items-center gap-3 text-sm font-medium"><Checkbox checked={visible.length > 0 && visible.every((p) => selectedIds.has(p.id))} onCheckedChange={(v) => toggleVisible(Boolean(v))}/>Sélectionner cette page</label><span className="text-xs text-muted-foreground">{selectedIds.size} élève(s) sélectionné(s)</span></div>
    <div className="grid gap-3 p-4 md:grid-cols-2 xl:hidden">{visible.map(p=><article key={p.id} className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><label className="grid size-11 shrink-0 cursor-pointer place-items-center rounded-lg bg-slate-50"><Checkbox aria-label={`Sélectionner ${p.firstName} ${p.lastName}`} checked={selectedIds.has(p.id)} onCheckedChange={v=>{const next=new Set(selectedIds);if(v)next.add(p.id);else next.delete(p.id);onSelectedIdsChange(next);}}/></label><div className="min-w-0 flex-1"><p className="font-semibold">{p.lastName.toLocaleUpperCase("fr")}</p><p className="text-sm text-muted-foreground">{p.firstName}</p></div><span className="rounded-lg bg-blue-50 px-2.5 py-2 font-mono text-sm font-bold text-primary">#{p.bibNumber}</span></div><div className="mt-4 flex flex-wrap items-center gap-2 text-sm"><span className="font-medium">{p.className||"Classe à renseigner"}</span><span className="text-muted-foreground">· {p.sex||"Sexe non renseigné"}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{!p.issues.length?<Badge className="bg-emerald-50 text-emerald-700">Valide</Badge>:p.issues.map(i=><Badge key={i.code} variant="outline" className={i.severity==="error"?"border-red-200 bg-red-50 text-red-700":"border-amber-200 bg-amber-50 text-amber-700"}>{i.message}</Badge>)}</div><div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-3"><Button variant="outline" size="sm" className="mr-auto" onClick={()=>onReprint(p.id)}><Printer/>Réimprimer</Button><Button size="icon-sm" variant="ghost" aria-label={`Modifier ${p.firstName} ${p.lastName}`} onClick={()=>{setEdited(p);setEditorOpen(true);}}><Pencil/></Button><Button size="icon-sm" variant="ghost" aria-label={`Supprimer ${p.firstName} ${p.lastName}`} className="text-red-600" onClick={()=>setDeleteCandidate(p)}><Trash2/></Button></div></article>)}</div>
    <div className="cross-scroll hidden xl:block"><table className="cross-table min-w-[980px]"><thead className="bg-slate-50"><tr><th aria-label="Sélection"/><th>N°</th><th>Participant</th><th>Classe</th><th>Sexe</th><th>Identifiant</th><th>Contrôle</th><th className="text-right">Actions</th></tr></thead><tbody>{visible.map((p) => <tr key={p.id}><td><label className="grid size-11 cursor-pointer place-items-center"><Checkbox aria-label={`Sélectionner ${p.firstName} ${p.lastName}`} checked={selectedIds.has(p.id)} onCheckedChange={(v) => {const next=new Set(selectedIds);if(v)next.add(p.id);else next.delete(p.id);onSelectedIdsChange(next);}}/></label></td><td className="font-bold text-primary">{p.bibNumber}</td><td className="min-w-36"><b>{p.lastName.toLocaleUpperCase("fr")}</b><br/><span className="text-muted-foreground">{p.firstName}</span></td><td>{p.className||"—"}</td><td>{p.sex||"—"}</td><td className="font-mono text-xs">{p.technicalId}</td><td className="max-w-56">{!p.issues.length ? <Badge className="bg-emerald-50 text-emerald-700">Valide</Badge> : <div className="flex flex-wrap gap-1">{p.issues.map((i) => <Badge key={i.code} variant="outline" className={i.severity === "error" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}>{i.message}</Badge>)}</div>}</td><td><div className="flex justify-end gap-1"><Button size="icon-sm" variant="ghost" aria-label={`Réimprimer ${p.firstName} ${p.lastName}`} onClick={() => onReprint(p.id)}><Printer/></Button><Button size="icon-sm" variant="ghost" aria-label={`Modifier ${p.firstName} ${p.lastName}`} onClick={() => {setEdited(p);setEditorOpen(true);}}><Pencil/></Button><Button size="icon-sm" variant="ghost" aria-label={`Supprimer ${p.firstName} ${p.lastName}`} className="text-red-600" onClick={() => setDeleteCandidate(p)}><Trash2/></Button></div></td></tr>)}</tbody></table></div>
    {!visible.length&&<p className="p-8 text-center text-sm text-muted-foreground">Aucun élève ne correspond à ces filtres.</p>}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm"><span className="text-muted-foreground">{filtered.length} résultats · page {currentPage}/{pages}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={currentPage<=1} onClick={() => setPage((v)=>v-1)}>Précédent</Button><Button size="sm" variant="outline" disabled={currentPage>=pages} onClick={() => setPage((v)=>v+1)}>Suivant</Button></div></div>
   </>}
  </section>
  <MappingDialog draft={draft} open={mappingOpen} onOpenChange={setMappingOpen} onConfirm={confirmMapping}/>
  <ParticipantDialog participant={edited} open={editorOpen} onOpenChange={setEditorOpen} onSave={(values) => { if (edited) update(participants.map((p) => p.id === edited.id ? {...p,...values}:p)); else {const bibNumber=nextAvailableNumber(participants,event.numbering.start);update([...participants,{id:createLocalId(),sourceRow:0,bibNumber,technicalId:technicalId(event.numbering,bibNumber),...values,issues:[]}]);} toast.success(edited?"Participant modifié.":"Participant ajouté."); }}/>
  <AlertDialog open={Boolean(replacement)} onOpenChange={(open)=>!open&&setReplacement(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remplacer la liste actuelle ?</AlertDialogTitle><AlertDialogDescription>Les {participants.length} participants actuels seront remplacés par {replacement?.length??0} lignes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction className="bg-red-600" onClick={() => {if(replacement&&draft){onChange({...event,participants:replacement,sourceFileName:draft.fileName});onSelectedIdsChange(new Set());toast.success(`${replacement.length} participants importés.`);setReplacement(undefined);}}}>Remplacer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={Boolean(deleteCandidate)} onOpenChange={(open)=>!open&&setDeleteCandidate(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer ce participant ?</AlertDialogTitle><AlertDialogDescription>{deleteCandidate?.firstName} {deleteCandidate?.lastName} sera retiré sans renuméroter les autres.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction className="bg-red-600" onClick={() => {if(deleteCandidate){update(participants.filter((p)=>p.id!==deleteCandidate.id));const next=new Set(selectedIds);next.delete(deleteCandidate.id);onSelectedIdsChange(next);setDeleteCandidate(undefined);}}}>Supprimer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
