"use client";
import { useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, FileSpreadsheet, Pencil, Plus, Printer, Search, Trash2, UploadCloud, Users } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { MappingDialog } from "./mapping-dialog";
import { ParticipantDialog } from "./participant-dialog";
import { importParticipants, readParticipantFile } from "@/lib/dossard/import";
import { createLocalId, nextAvailableNumber, renumberParticipants, sanitizePrefix, technicalId } from "@/lib/dossard/identifiers";
import type { ColumnMapping, ImportDraft, Participant, RaceEvent } from "@/lib/dossard/types";
import { validateParticipants } from "@/lib/dossard/validation";
const PAGE_SIZE = 30;
type IssueFilter = "all" | "errors" | "warnings";
interface Props { event: RaceEvent; onChange: (event: RaceEvent) => void; selectedIds: Set<string>; onSelectedIdsChange: (ids: Set<string>) => void; onReprint: (id: string) => void; issueFilter: IssueFilter; onIssueFilterChange: (filter: IssueFilter) => void; }
export function ParticipantsStep({ event, onChange, selectedIds, onSelectedIdsChange, onReprint, issueFilter, onIssueFilterChange }: Props) {
 const fileRef = useRef<HTMLInputElement>(null); const [draft,setDraft] = useState<ImportDraft>(); const [mappingOpen,setMappingOpen] = useState(false); const [replacement,setReplacement] = useState<Participant[]>(); const [search,setSearch] = useState(""); const [classFilter,setClassFilter] = useState("all"); const [page,setPage] = useState(1); const [editorOpen,setEditorOpen] = useState(false); const [edited,setEdited] = useState<Participant|null>(null); const [deleteCandidate,setDeleteCandidate] = useState<Participant>(); const participants = event.participants;
 const classes = useMemo(() => [...new Set(participants.map((p) => p.className).filter(Boolean))].sort((a,b) => a.localeCompare(b,"fr")), [participants]);
 const errors = participants.reduce((sum,p) => sum + p.issues.filter((i) => i.severity === "error").length, 0), duplicates = participants.filter((p) => p.issues.some((i) => i.code === "possible-duplicate")).length;
 const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase("fr"); return participants.filter((p) => (!q || [p.lastName,p.firstName,p.className,p.technicalId].some((v) => v.toLocaleLowerCase("fr").includes(q))) && (classFilter === "all" || p.className === classFilter) && (issueFilter === "all" || (issueFilter === "errors" ? p.issues.some((i) => i.severity === "error") : p.issues.some((i) => i.severity === "warning")))); }, [participants,search,classFilter,issueFilter]); const pages = Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)), currentPage = Math.min(page,pages), visible = filtered.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
 const update = (next: Participant[]) => onChange({ ...event, participants: validateParticipants(next) });
 const processFile = async (file?: File) => { if (!file) return; try { const next = await readParticipantFile(file); setDraft(next); setMappingOpen(true); } catch (error) { toast.error(error instanceof Error ? error.message : "Import impossible."); } };
 const confirmMapping = (mapping: ColumnMapping) => { if (!draft) return; const imported = importParticipants(draft,mapping,event.numbering); setMappingOpen(false); if (participants.length) setReplacement(imported); else { onChange({ ...event, participants: imported, sourceFileName: draft.fileName }); toast.success(`${imported.length} participants importés.`); } };
 const number = (patch: Partial<RaceEvent["numbering"]>) => { const numbering = { ...event.numbering, ...patch }; numbering.prefix = sanitizePrefix(numbering.prefix); numbering.start = Math.max(0,Number.isFinite(numbering.start) ? numbering.start : 1); numbering.digits = Math.max(1,Math.min(8,Number.isFinite(numbering.digits) ? numbering.digits : 4)); onChange({ ...event, numbering, participants: validateParticipants(renumberParticipants(participants,numbering)) }); };
 const toggleVisible = (checked: boolean) => { const next = new Set(selectedIds); visible.forEach((p) => checked ? next.add(p.id) : next.delete(p.id)); onSelectedIdsChange(next); };
 return <div className="space-y-6">
  <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
   <div className="race-card group flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-[1.6rem] border-2 border-dashed border-blue-200 bg-white px-6 py-8 text-center transition hover:border-[#1154b3] hover:bg-blue-50/40" onClick={() => fileRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); void processFile(e.dataTransfer.files[0]); }}><span className="mb-3 grid size-14 place-items-center rounded-2xl bg-[#fff1a3] text-[#1154b3]"><UploadCloud /></span><h2 className="text-lg font-black">{participants.length ? "Importer un nouveau fichier" : "Déposez votre liste"}</h2><p className="mt-1 text-sm text-slate-500">Nom, prénom, classe et sexe · XLSX, XLS ou CSV</p><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={(e) => { void processFile(e.target.files?.[0]); e.target.value = ""; }} /></div>
   <aside className="race-band race-card rounded-[1.6rem] p-5 text-white"><div className="mb-4 flex items-center gap-2"><FileSpreadsheet className="text-[#fed60b]"/><h2 className="font-bold">Numérotation</h2></div><div className="grid grid-cols-2 gap-3"><div className="col-span-2"><Label className="mb-1 text-blue-100">Préfixe</Label><Input value={event.numbering.prefix} maxLength={16} className="border-white/20 bg-white/10 text-white" onChange={(e) => number({prefix:e.target.value})}/></div><div><Label className="mb-1 text-blue-100">Départ</Label><Input type="number" value={event.numbering.start} className="border-white/20 bg-white/10 text-white" onChange={(e) => number({start:Number(e.target.value)})}/></div><div><Label className="mb-1 text-blue-100">Chiffres</Label><Input type="number" min={1} max={8} value={event.numbering.digits} className="border-white/20 bg-white/10 text-white" onChange={(e) => number({digits:Number(e.target.value)})}/></div></div><div className="mt-4 rounded-xl bg-black/15 p-3"><p className="text-xs uppercase tracking-wider text-blue-200">Exemple</p><p className="mt-1 font-mono text-xl font-bold text-[#fed60b]">{technicalId(event.numbering,event.numbering.start)}</p></div></aside>
  </section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:"Participants",value:participants.length,icon:Users,tone:"blue"},{label:"Classes",value:classes.length,icon:CheckCircle2,tone:"blue"},{label:"Erreurs",value:errors,icon:AlertCircle,tone:errors?"red":"green"},{label:"Doublons potentiels",value:duplicates,icon:AlertCircle,tone:duplicates?"amber":"green"}].map((s) => <div key={s.label} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><span className="text-sm text-slate-500">{s.label}</span><s.icon className={`size-4 ${s.tone === "red" ? "text-red-500" : s.tone === "amber" ? "text-amber-500" : s.tone === "green" ? "text-emerald-500" : "text-blue-600"}`}/></div><p className="mt-2 text-3xl font-black">{s.value}</p></div>)}</section>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={(e) => {setSearch(e.target.value);setPage(1);}} placeholder="Rechercher un nom, une classe ou un numéro…" className="pl-9"/></div><Select value={classFilter} onValueChange={(v) => {setClassFilter(v);setPage(1);}}><SelectTrigger className="w-full lg:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les classes</SelectItem>{classes.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={issueFilter} onValueChange={(v) => {onIssueFilterChange(v as IssueFilter);setPage(1);}}><SelectTrigger className="w-full lg:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les lignes</SelectItem><SelectItem value="errors">Avec erreurs</SelectItem><SelectItem value="warnings">Avec alertes</SelectItem></SelectContent></Select><Button variant="outline" onClick={() => {setEdited(null);setEditorOpen(true);}}><Plus/> Ajouter</Button></div>
   {!participants.length ? <div className="grid min-h-48 place-items-center p-10 text-center"><div><Users className="mx-auto mb-3 text-slate-300"/><p className="font-semibold">Aucun participant importé</p></div></div> : <><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-blue-50/70 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3"><Checkbox checked={visible.length > 0 && visible.every((p) => selectedIds.has(p.id))} onCheckedChange={(v) => toggleVisible(Boolean(v))}/></th><th>N°</th><th>Participant</th><th>Classe</th><th>Sexe</th><th>Identifiant</th><th>Contrôle</th><th className="px-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{visible.map((p) => <tr key={p.id} className="hover:bg-blue-50/50"><td className="px-4 py-3"><Checkbox checked={selectedIds.has(p.id)} onCheckedChange={(v) => {const next=new Set(selectedIds);if(v)next.add(p.id);else next.delete(p.id);onSelectedIdsChange(next);}}/></td><td className="font-black text-[#1154b3]">{p.bibNumber}</td><td className="py-3"><b>{p.lastName.toLocaleUpperCase("fr")}</b><br/><span className="text-slate-500">{p.firstName}</span></td><td>{p.className||"—"}</td><td>{p.sex||"—"}</td><td className="font-mono text-xs">{p.technicalId}</td><td>{!p.issues.length ? <Badge className="bg-emerald-50 text-emerald-700">Valide</Badge> : <div className="flex flex-wrap gap-1">{p.issues.map((i) => <Badge key={i.code} variant="outline" className={i.severity === "error" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}>{i.message}</Badge>)}</div>}</td><td className="px-4"><div className="flex justify-end"><Button size="icon-sm" variant="ghost" onClick={() => onReprint(p.id)}><Printer/></Button><Button size="icon-sm" variant="ghost" onClick={() => {setEdited(p);setEditorOpen(true);}}><Pencil/></Button><Button size="icon-sm" variant="ghost" className="text-red-600" onClick={() => setDeleteCandidate(p)}><Trash2/></Button></div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-4 text-sm"><span className="text-slate-500">{filtered.length} résultats · page {currentPage}/{pages}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={currentPage<=1} onClick={() => setPage((v)=>v-1)}>Précédent</Button><Button size="sm" variant="outline" disabled={currentPage>=pages} onClick={() => setPage((v)=>v+1)}>Suivant</Button></div></div></>}
  </section>
  <MappingDialog draft={draft} open={mappingOpen} onOpenChange={setMappingOpen} onConfirm={confirmMapping}/>
  <ParticipantDialog participant={edited} open={editorOpen} onOpenChange={setEditorOpen} onSave={(values) => { if (edited) update(participants.map((p) => p.id === edited.id ? {...p,...values}:p)); else {const bibNumber=nextAvailableNumber(participants,event.numbering.start);update([...participants,{id:createLocalId(),sourceRow:0,bibNumber,technicalId:technicalId(event.numbering,bibNumber),...values,issues:[]}]);} toast.success(edited?"Participant modifié.":"Participant ajouté."); }}/>
  <AlertDialog open={Boolean(replacement)} onOpenChange={(open)=>!open&&setReplacement(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remplacer la liste actuelle ?</AlertDialogTitle><AlertDialogDescription>Les {participants.length} participants actuels seront remplacés par {replacement?.length??0} lignes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction className="bg-red-600" onClick={() => {if(replacement&&draft){onChange({...event,participants:replacement,sourceFileName:draft.fileName});onSelectedIdsChange(new Set());toast.success(`${replacement.length} participants importés.`);setReplacement(undefined);}}}>Remplacer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={Boolean(deleteCandidate)} onOpenChange={(open)=>!open&&setDeleteCandidate(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer ce participant ?</AlertDialogTitle><AlertDialogDescription>{deleteCandidate?.firstName} {deleteCandidate?.lastName} sera retiré sans renuméroter les autres.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction className="bg-red-600" onClick={() => {if(deleteCandidate){update(participants.filter((p)=>p.id!==deleteCandidate.id));const next=new Set(selectedIds);next.delete(deleteCandidate.id);onSelectedIdsChange(next);setDeleteCandidate(undefined);}}}>Supprimer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
