"use client";
import { useRef, useState } from "react";
import { FileImage, ImagePlus, Library, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { StepHeading } from "./step-heading";
import { BibCanvas } from "./bib-canvas";
import { backgroundQuality, readBackgroundFile } from "@/lib/dossard/files";
import type { BibTemplate, RaceEvent } from "@/lib/dossard/types";
export function TemplateStep({ event, templates, onChange, onSaveTemplate }: { event: RaceEvent; templates: BibTemplate[]; onChange: (event: RaceEvent) => void; onSaveTemplate: (template: BibTemplate) => Promise<void> }) { const fileRef=useRef<HTMLInputElement>(null); const [removeOpen,setRemoveOpen]=useState(false); const [saveOpen,setSaveOpen]=useState(false); const [name,setName]=useState(event.template.name); const background=event.template.background, quality=background?backgroundQuality(background):undefined; const importBg=async(file?:File)=>{if(!file)return;try{const asset=await readBackgroundFile(file);onChange({...event,template:{...event.template,background:asset,updatedAt:new Date().toISOString()}});toast.success("Fond importé.");}catch(error){toast.error(error instanceof Error?error.message:"Import impossible.");}}; const ratioWarning=background?Math.abs(background.widthPx/background.heightPx-event.template.widthMm/event.template.heightMm)>.035:false; return <div className="space-y-6">
  <StepHeading icon={FileImage} title="Fond des dossards" description="Utilisez le fond par défaut ou importez votre visuel au format A5 paysage." /><section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div className="cross-panel bg-[#f0f5ff] p-4 sm:p-7"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1154b3]">Aperçu du fond</p><h2 className="mt-1 text-lg font-bold">A5 paysage · 210 × 148 mm</h2></div>{quality&&<Badge className={quality.level==="good"?"bg-emerald-100 text-emerald-800":quality.level==="medium"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800"}>{quality.label}</Badge>}</div><BibCanvas event={event} participant={event.participants[0]} interactive={false} grid={false}/>{!background&&<p className="mt-4 text-sm text-slate-600">Le cadre par défaut est déjà imprimable. Vous pouvez le remplacer.</p>}</div><aside className="space-y-4"><div role="button" tabIndex={0} aria-label="Importer un fond de dossard" onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();fileRef.current?.click();}}} className="flex min-h-52 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-white p-6 text-center hover:border-[#1154b3]" onClick={()=>fileRef.current?.click()} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();void importBg(e.dataTransfer.files[0]);}}><span className="mb-3 grid size-12 place-items-center rounded-2xl bg-[#fff3a9] text-[#1154b3]"><ImagePlus/></span><h2 className="font-bold">{background?"Remplacer le fond":"Importer votre fond"}</h2><p className="text-sm text-slate-500">PNG ou JPEG · 30 Mo max.</p><input ref={fileRef} type="file" accept="image/png,image/jpeg" className="hidden" onChange={(e)=>{void importBg(e.target.files?.[0]);e.target.value="";}}/></div>{background&&<div className="cross-panel p-4"><div className="flex gap-3"><FileImage className="shrink-0 text-primary"/><div><p className="break-all font-bold">{background.fileName}</p><p className="text-sm text-slate-500">{background.widthPx} × {background.heightPx} px · {(background.sizeBytes/1048576).toFixed(1)} Mo</p><p className={`mt-2 text-sm ${ratioWarning?"text-amber-700":"text-emerald-700"}`}>{ratioWarning?"L’image sera centrée sans déformation, avec marge éventuelle.":"Ratio adapté au A5 paysage."}</p></div></div><Button variant="ghost" className="mt-3 w-full text-red-600" onClick={()=>setRemoveOpen(true)}><Trash2/> Supprimer le fond</Button></div>}<Button className="w-full" onClick={()=>{setName(event.template.name);setSaveOpen(true);}}><Save/> Enregistrer comme modèle</Button></aside></section>
 <section className="cross-panel p-5"><div className="mb-4 flex gap-2"><Library className="shrink-0 text-primary"/><div><h2 className="font-bold">Mes modèles</h2><p className="text-sm text-slate-500">Réutilisez le fond et toute la mise en page.</p></div></div>{!templates.length?<p className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Aucun modèle sauvegardé.</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{templates.map((t)=><article key={t.id} className="rounded-xl border p-4"><h3 className="font-bold">{t.name}</h3><p className="text-sm text-slate-500">{t.elements.length} éléments · {t.background?"fond inclus":"sans fond"}</p><Button size="sm" variant="outline" className="mt-4 w-full" onClick={()=>{onChange({...event,template:structuredClone(t)});toast.success(`Modèle « ${t.name} » appliqué.`);}}>Utiliser</Button></article>)}</div>}</section>
 <Dialog open={saveOpen} onOpenChange={setSaveOpen}><DialogContent><DialogHeader><DialogTitle>Enregistrer le modèle</DialogTitle><DialogDescription>Le fond et les positions seront conservés localement.</DialogDescription></DialogHeader><Label>Nom du modèle</Label><Input value={name} onChange={(e)=>setName(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setSaveOpen(false)}>Annuler</Button><Button disabled={!name.trim()} onClick={async()=>{const saved={...structuredClone(event.template),name:name.trim(),updatedAt:new Date().toISOString()};await onSaveTemplate(saved);onChange({...event,template:saved});setSaveOpen(false);toast.success("Modèle sauvegardé.");}}>Enregistrer</Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={removeOpen} onOpenChange={setRemoveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer le fond ?</AlertDialogTitle><AlertDialogDescription>Les éléments resteront en place.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction className="bg-red-600" onClick={()=>{const template={...event.template,background:undefined};onChange({...event,template});}}>Supprimer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>; }
