"use client";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, Check, CheckCircle2, LockKeyhole, ScanBarcode, ShieldCheck, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BarcodePreview } from "./code-preview";
import { previewElementValue } from "@/lib/dossard/preview";
import type { RaceEvent } from "@/lib/dossard/types";
import { buildValidationChecks, isEventReady } from "@/lib/dossard/validation";
function reductions(event:RaceEvent){if(typeof document==="undefined")return 0;const ctx=document.createElement("canvas").getContext("2d");if(!ctx)return 0;const elements=event.template.elements.filter((e)=>!["barcode","qrcode"].includes(e.type));return event.participants.filter((p)=>elements.some((e)=>{ctx.font=`${e.italic?"italic ":""}${e.bold?700:400} ${e.fontSizePt*96/72}px DejaVu Sans,Arial`;return ctx.measureText(previewElementValue(e,p,event)).width>e.widthMm*96/25.4-6;})).length;}
export function VerificationStep({event,onContinue}:{event:RaceEvent;onContinue:()=>void}){const checks=useMemo(()=>buildValidationChecks(event),[event]),reduced=useMemo(()=>reductions(event),[event]),expected=event.participants[0]?.technicalId??"",inputRef=useRef<HTMLInputElement>(null);const[value,setValue]=useState(""),[result,setResult]=useState<"idle"|"success"|"error">("idle"),ready=isEventReady(event);const evaluate=()=>setResult(value.trim()===expected?"success":"error");return <div className="space-y-6"><section className={`rounded-2xl border p-5 ${ready?"border-emerald-200 bg-emerald-50":"border-red-200 bg-red-50"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className={`grid size-11 place-items-center rounded-2xl text-white ${ready?"bg-emerald-600":"bg-red-600"}`}>{ready?<Check/>:<X/>}</span><div><h2 className="text-xl font-black">{ready?"Prêt pour la génération":"Corrections nécessaires"}</h2><p className="text-sm text-slate-600">{ready?"Tous les contrôles bloquants sont validés.":"Corrigez les lignes signalées avant le PDF."}</p></div></div><Button disabled={!ready} onClick={onContinue}>Passer à l’export</Button></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{checks.map((c)=><article key={c.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{c.label}</p><p className="text-2xl font-black">{c.value}</p></div><span className={`grid size-8 place-items-center rounded-full ${c.status==="ok"?"bg-emerald-100 text-emerald-700":c.status==="warning"?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700"}`}>{c.status==="ok"?<Check/>:<AlertTriangle/>}</span></div>{c.detail&&<p className="mt-2 text-sm text-slate-500">{c.detail}</p>}</article>)}</section>{reduced>0&&<section className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="text-amber-700"/><div><p className="font-bold text-amber-900">{reduced} participant{reduced>1?"s nécessitent":" nécessite"} une taille réduite</p><p className="text-sm text-amber-800">Aucun nom ne sera coupé.</p></div></section>}
 <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.75fr)]"><div className="rounded-2xl border bg-white p-5"><div className="mb-5 flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#0d397b] text-white"><ScanBarcode/></span><div><h2 className="font-black">Tester la douchette</h2><p className="text-sm text-slate-500">Scannez le code test puis vérifiez la valeur reçue.</p></div></div>{expected?<><div className="mx-auto h-24 max-w-md rounded-xl border p-2"><BarcodePreview value={expected}/></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><Input ref={inputRef} value={value} onChange={(e)=>{setValue(e.target.value);setResult("idle");}} onKeyDown={(e)=>e.key==="Enter"&&evaluate()} placeholder="Cliquez ici puis scannez" className="font-mono"/><Button variant="outline" onClick={()=>{setValue("");setResult("idle");inputRef.current?.focus();}}>Démarrer</Button><Button disabled={!value} onClick={evaluate}>Vérifier</Button></div>{result==="success"&&<p className="mt-3 flex gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><CheckCircle2/> Scanner correctement configuré : {value.trim()}</p>}{result==="error"&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">Reçu : {value.trim()||"vide"} · attendu : {expected}</p>}</>:<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Importez un participant.</p>}</div><aside className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex gap-2 text-blue-900"><ShieldCheck/><h2 className="font-black">Confidentialité vérifiée</h2></div><ul className="mt-4 space-y-3 text-sm"><li className="flex gap-2"><Check className="text-emerald-600"/>Les fichiers restent dans ce navigateur.</li><li className="flex gap-2"><Check className="text-emerald-600"/>Les codes contiennent uniquement l’identifiant.</li><li className="flex gap-2"><Check className="text-emerald-600"/>Aucune liste n’est publiée.</li></ul><div className="mt-5 flex gap-2 rounded-xl bg-white/70 p-3 text-sm text-blue-900"><LockKeyhole/>Les données sont liées à cet appareil.</div></aside></section></div>;}
